### ISSUE TITLE
(Feature) Add token: disable fields decimals and symbol if autofill is succesfull

### ISSUE THREAD

**Issue by dennis00010011b** [poanetwork/metamask-extension#126]
See https://github.com/poanetwork/metamask-extension/pull/121#issuecomment-420004477

Symbol and decimals are trying to be autofilled from contract address. In the case of successful autofill, we shouldn't allow a user to change decimals and symbol. Thus,

 - if autofill is successful, we display auto-filled values and disable symbol and decimals fields.
 - if autofill is not successful (for any reason), we keep symbol and decimals editable for manual fill.
Would you mind of such a proposal?

**Comment by vbaranov** [comment]
@dennis00010011b I revised your original proposal https://github.com/poanetwork/metamask-extension/pull/121#pullrequestreview-153798293 and think we could implement it. Indeed, decimals are defined in a token contract. And, it seems, there are no cases where we need to redefine decimals in the wallet. It doesn't work for a symbol, though - a user should be able to change it in the wallet, because there are tokens with the same symbol can exist in the same network and user should be able to differentiate them. In addition, I don't see the cases where tokens should be added, if autofill doesn't work. Moreover, an addition of incorrect token addresses can result in errors in getting of tokens' balances. Thus, we need to validate token contract before addition to the list. So, I would like to implement it in the next PR:
- disabling of decimals field
- prohibition to add custom token if metadata is not auto-filled.
