### ISSUE TITLE
NIFTY Wallet doesn't always pop up when click triggered in web3

### ISSUE THREAD

**Issue by radamosch** [poanetwork/metamask-extension#19]
When click button on dApp, the wallet should open, but instead it sits with number of tx indicated.

![image](https://user-images.githubusercontent.com/35626984/43044848-e4eeae4c-8da5-11e8-836c-020d85716939.png)

This can sometimes also happen with MM, but it *seems to happen a lot with NIFTY

**Comment by vbaranov** [comment]
@radamosch could you clarify 
- which network could I reproduce this behaviour with?
- which type of tx: ether transfer, contract method execution?
- what is the origin of tx: if this is DApp, which one?

**Comment by radamosch** [comment]
That i can see it happens nearly every time and MANY users think nothing is happening.
It happens even just in remix when testing a contract.

If you can't reproduce this i would be totally shocked :)

**Comment by radamosch** [comment]
I realise now it could be related to the positioning of the NIFTY window behind the browser window:

![image](https://user-images.githubusercontent.com/35626984/43154895-c5542642-8f6d-11e8-87ef-d450fabc641f.png)

Although this is not always the reason. it simply just doesn't show up. This is in chrome anyway, we dont' have a FF build yet.

This is major irritation for users (even when it happens on MM)

**Comment by vbaranov** [comment]
@radamosch yes, I can reproduce NW is behind the main window. It sometimes happens if I reject the previous transaction and close the popup. Will take a look at what we can do with this.

**Comment by vbaranov** [comment]
@radamosch 

These features were implemented in NW@8.4.5:

- Force focus to notification popup if it is already opened because it can be hidden behind the DApp
- Close notification window if action was confirmed in the popup or from notification window itself
- Close notification window if all transactions were rejected at once from the popup or from notification window itself.

All of them should resolve your problem. If an issue with a hidden notification popup will appear again, please let us know the scenario to reproduce in a new issue.
